#!/usr/bin/python

import sys, csv, string

def mapper():
	'''
	mapper_toptags.py, reducer_toptags.py
	Find which students have posted under threads with the same tag.
	Work on data from the udacity forum (similar to Stack Exchange format). 
	The dataset for this mapper was generated by exporting data from a SQL database.

	Input:
	======
	Read forum_node.tsv. The format of each line from forum_node.tsv is
	id title tagnames author_id body node_type parent_id abs_parent_id added_at score state_string last_edited_id last_activity_by_id...
	last_actitvity_at active_revision_id extra extra_ref_id extra_count marked 
	We need to extract the post id and the author_id. For questions, the post id is under "id", for answers and comments it is under "abs_parent_id" 

	Output:
	=======
	For each entry in forum_node.tsv, output a line of the form: 
	post_id\tuser_id
	'''

	reader = csv.reader(sys.stdin, delimiter='\t') 	# read line by line, split input at \t characters

	for line in reader:
		if line[0] == "id":	# first line is just title
			continue
		elif len(line) == 19:
			# get the user id, and thread id (post_id)
			user_id = line[3]
			post_type = line[5]
			if post_type == "question": # for questions, the id is under the "id" column
				post_id = line[0]
			elif post_type == "answer" or post_type=="comment": # for answers and comments the id is in the "abs_parent_id" column
				post_id = line[7]

			print "{0}\t{1}".format(post_id, user_id)
		else:	# something went wrong, skip badly formatted data
			continue

if __name__=="__main__":
	mapper()

