#!/usr/bin/python

import sys, string

def reducer():
	'''
	mapper_length.py, reducer_length.py
	Work on data from the udacity forum (similar to Stack Exchange format). 
	Use the user post data to find which students have posted under threads with the same tag.
	The dataset for this mapper was generated by exporting data from a SQL database.

	Input:
	======
	The feed from the mapper is:
	post_id\tuser_id
	and it comes sorted, which means I get all the answers for a  particular id, then I get the comments, and the question for that id.

	Output:
	=======
	For each entry in forum_node.tsv, output a line of the form: 
	post_id\t[user_id]
	'''
	oldId = None
	thisId = None
	authorList = []

	for line in sys.stdin:
		data_mapped = line.strip().split("\t")
		if len(data_mapped) != 2:# Something has gone wrong. Skip this line.
			continue

		thisId, thisAuthor = data_mapped	# get the new entry	    

		if oldId and oldId != thisId:		# if there is a new user, print the results for the previous user
			print "{0}\t{1}".format(oldId, authorList)
			# don't forget to reset the list
			authorList = []

		# update the user, total length, counts 
		oldId = thisId
		authorList.append(int(thisAuthor))

	if oldId != None:# finally, print the last entry
		print "{0}\t{1}".format(oldId, authorList)

if __name__=="__main__":
	reducer()
