#!/usr/bin/python

'''
Create an inverted index of the words found in the body of each node of the forum, 
i.e. index word, nodeid_1, nodeid_2, ...
Work on data from the udacity forum (similar to Stack Exchange format). 
The dataset for this mapper was generated by exporting data from a SQL database.

The data in at least one of the fields (the body field) can include newline
characters, and all the fields are enclosed in double quotes. Therefore, we
will need to process the data file in a way other than using split(","). To do this, 
we have provided sample code for using the csv module of Python. Each 'line'
will be a list that contains each field in sequential order.
 
In this exercise, we are interested in the field 'body' (which is the 5th field, 
line[4]).

Mapper has returned (word, node_id) pairs for each word in the body of each entry. 
'''

import sys, string

oldKey = None
nodeList = []

for line in sys.stdin:
	data_mapped = line.strip().split("\t")
	if len(data_mapped) != 2:
		# Something has gone wrong. Skip this line.
		continue

	thisKey, thisNode = data_mapped

	if oldKey and oldKey != thisKey:
		nodeList.sort()
		numNodes = len(nodeList)
		nodeStr = string.join(nodeList,"\t")
		print "{0}\t{1}\tTotal\t{2}".format(oldKey,nodeStr,str(numNodes))
		oldKey = thisKey; # reduntant but whatever
		nodeList = []        

	oldKey = thisKey
	nodeList.append(thisNode.strip('\"'))

if oldKey != None:
	nodeList.sort()
	numNodes = len(nodeList)
	nodeStr = string.join(nodeList,"\t")
	print "{0}\t{1}\tTotal\t{2}".format(oldKey,nodeStr,str(numNodes))

